version: '3.8'

services:
  web:
    image: chachap-dev:latest
    build: 
      dockerfile: Dockerfile.dev
    container_name: "chachapp-dev"
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  postgres:
    image: postgres:13-alpine
    container_name: "chach-db"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ${DOCKERDIR}/bin/webdb_dock:/bin/webdb
      - ${DOCKERDIR}/sql/schema.sql:/sql/schema.sql
      - ${DOCKERDIR}/sql/data.sql:/sql/data.sql
      - ${DOCKERDIR}/sql/uploads/:/sql/uploads/
    ports:
      - 5432:5432
    env_file:
      - ./.env.dev.db
    # environment:
    #   - POSTGRES_USER=ryanmagyar
    #   - POSTGRES_PASSWORD=nintendo11
    #   - POSTGRES_DB=chachfilms
  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
volumes:
  portainer_data:
  postgres_data:

